---
- name: Pull docker image of the Calculator
  hosts: all
  tasks:
    - name: pull docker image
      shell: docker pull coolgopalgoyal/minirpojectcalculator048

    - name: running container
      shell: docker run --name miniproject -d coolgopalgoyal/minirpojectcalculator048 
      
    - name: running jar file
      shell: docker exec -it miniproject java -jar MiniDevopsCalculator-1.0-SNAPSHOT-jar-with-dependencies.jar bash
